// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIbnBkadKfi75tUwIZOQYUHcNl_rFgMMQ',
    appId: '1:324725989859:web:44b054da53e67ebfdbc0d6',
    messagingSenderId: '324725989859',
    projectId: 'online-shop-admin-d07af',
    authDomain: 'online-shop-admin-d07af.firebaseapp.com',
    storageBucket: 'online-shop-admin-d07af.firebasestorage.app',
    measurementId: 'G-VQ1T2X7GSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfSav2a2v30pSK3g10rpXvmpW-EdxO00',
    appId: '1:324725989859:android:8ebb8c981b72ce52dbc0d6',
    messagingSenderId: '324725989859',
    projectId: 'online-shop-admin-d07af',
    storageBucket: 'online-shop-admin-d07af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9abGpCbPXGuHihIKkEVb3mSnc2721pc',
    appId: '1:324725989859:ios:1725718767089996dbc0d6',
    messagingSenderId: '324725989859',
    projectId: 'online-shop-admin-d07af',
    storageBucket: 'online-shop-admin-d07af.firebasestorage.app',
    iosBundleId: 'com.example.userOnlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9abGpCbPXGuHihIKkEVb3mSnc2721pc',
    appId: '1:324725989859:ios:1725718767089996dbc0d6',
    messagingSenderId: '324725989859',
    projectId: 'online-shop-admin-d07af',
    storageBucket: 'online-shop-admin-d07af.firebasestorage.app',
    iosBundleId: 'com.example.userOnlineShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIbnBkadKfi75tUwIZOQYUHcNl_rFgMMQ',
    appId: '1:324725989859:web:69a6fa3b7c986e0bdbc0d6',
    messagingSenderId: '324725989859',
    projectId: 'online-shop-admin-d07af',
    authDomain: 'online-shop-admin-d07af.firebaseapp.com',
    storageBucket: 'online-shop-admin-d07af.firebasestorage.app',
    measurementId: 'G-37BDZC29DG',
  );
}
